### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by rdeits** [JuliaRobotics/LCMCore.jl#30]
We should release a new version with the updated LCMType interface. @tkoolen the old API of defining fingerprint(), resize!(), etc. still works, right? So I think this can be a patch release rather than a minor version.

**Comment by tkoolen** [comment]
Let me just check real quick. I'll be in the lab in 30 minutes.

**Comment by tkoolen** [comment]
Nope. Unless I undo changes to the exported bindings and some method renames, e.g. `size_fields` -> `sizefields`. I can if you think it's worth it.

**Comment by rdeits** [comment]
Ok, this will be resolved as soon as I get attobot working again.
