### ISSUE TITLE
Unsafe arrays change seems to break encode/decode in v0.5.2

### ISSUE THREAD

**Issue by GearsAD** [JuliaRobotics/LCMCore.jl#56]
When I use LCMCore with the latest code and I use the log playback, it throws an error when decoding the UInt array:
```
ERROR: LoadError: MethodError: no method matching decode(::UnsafeArrays.UnsafeArray{UInt8,1}, ::Type{brookstone_supertype_t})
Closest candidates are:
  decode(::Array{UInt8,1}, ::Type{T<:LCMType}) where T<:LCMType at /home/gearsad/.julia/dev/LCMCore/src/lcmtype.jl:355
Stacktrace:
 [1] onresponse(::LCMCore.RecvBuf, ::Ptr{UInt8}, ::LCMCore.SubscriptionOptions{brookstone_supertype_t,getfield(Main, Symbol("##9#10"))}) at /home/gearsad/.julia/dev/LCMCore/src/core.jl:154
 [2] handle(::LCMLog) at /home/gearsad/.julia/dev/LCMCore/src/readlog.jl:97
 [3] top-level scope at ./none:0
 [4] include_string(::Module, ::String, ::String) at ./loading.jl:1005
...
```
 Ran the tests and they pass. I've jumped back to v0.5.1 and the issue goes away.

I'll try take a look this afternoon, but wanted to check if this rings any bells? It seems to be related to the new UnsafeArrays code.

**Comment by GearsAD** [comment]
It seems to be related to the convenience functions here [LCMType.jl:351-355](https://github.com/JuliaRobotics/LCMCore.jl/blob/master/src/lcmtype.jl#L351-L355).

If I change out the types to below, it functions correctly. Should I push this as a branch for review?

```julia
# Sugar
encode(data::UnsafeArrays.UnsafeArray{UInt8, 1}, x::LCMType) = encode(IOBuffer(data), x)
encode(x::LCMType) = (stream = FastWriteBuffer(); encode(stream, x); flush(stream); take!(stream))

decode!(x::LCMType, data::UnsafeArrays.UnsafeArray{UInt8, 1}) = decode!(x, IOBuffer(data))
decode(data::UnsafeArrays.UnsafeArray{UInt8, 1}, ::Type{T}) where {T<:LCMType} = decode!(T(), data)
```

**Comment by tkoolen** [comment]
I'll take a look. Could you provide a minimal example that results in the error so that I can use it as a test?

**Comment by GearsAD** [comment]
Thanks - sure, here is the one I'm currently working from:

```julia
using LCMCore, CaesarLCMTypes
using JSON

function lcm_NewOdoAvailable(channel, msg::brookstone_supertype_t)
    @show variable = msg.newvariable
end

lcmLog = LCMLog("brookstone_3.lcmlog")
subscribe(lcmLog, "BROOKSTONE_ROVER", (c,m)->lcm_NewOdoAvailable(c,m), brookstone_supertype_t)

# Run while there is data
while handle(lcmLog)
end
# Should fail as you call handle.
```

It needs a data file, I'm using this one for testing: [brookstone_3.lcmlog](https://github.com/GearsAD/GraffSDK.jl/blob/master/examples/data/brookstone_3.lcmlog)

**Comment by GearsAD** [comment]
Hi tkoolen,

I created a test this issue in a fork as I don't have push access - #59.

The test uses CaesarLCMTypes and adds another data file. 

I checked that your fix makes the test pass - looks good. 

Thank you for the fix.
